import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers"; // must be a client component
import { SocketContextProvider } from "../context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CelebrationStation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SocketContextProvider>
            {children}
          </SocketContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
